### PR TITLE
Log4rs v1

### PR DESCRIPTION
**Pull request by bheylin**
Hey @im-0 

I've made some adjustments to log4rs-syslog to bring it up to date with log4rs-1.0.0-alpha-2.
Are you interested in merging these into the main repo?

### CODE REVIEW

**Comment by gilescope** [comment]
Looks like 1.0.0 has been released now, so we could update to that.

**Comment by bheylin** [comment]
As expected, there were no issues upgrading to log4rs 1.0.0.

**Comment by gilescope** [comment]
Superstar!

**Comment by gilescope** [comment]
Could we get a new crate version published with this change please @im-0 ?

**Comment by rudolphfroger** [comment]
Would it be possible to make a release with this pull request included?

**Comment by rudolphfroger** [comment]
Any change this will be merged and released any time soon? No pressure :wink:

**Comment by a1ecbr0wn** [comment]
perhaps if @im-0 doesn't fancy updating the PR, a github org could be set up where others could update it?  It would be a shame to loose all of this great work

**Pull request closed without merging**
